language: node_js
node_js: "9"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm

install:
- yarn

script:
- if test -z "$TRAVIS_TAG"; then yarn run make; fi
# - cd node_modules/@electron-forge/maker-deb/ && yarn add --dev electron-installer-debian@1.1.0 && cd -
after_success: if test -n "$TRAVIS_TAG"; then yarn run publish; fi
